image: node:8-alpine

stages:
  - push

push to github:
  stage: push
  when: manual
  only:
    - github
  script:
    - apk add --update git
    - git remote add githubremote https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/sinergise/EOBrowser.git || echo "Already exists, ignoring."
    - git push githubremote origin/github:master
